## deep neural network implementation using tensorflow framework

In [1]:
import numpy as np
import tensorflow as tf
import sklearn.model_selection as sk


/home/robel/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
#define parameters
batch_size = 100
learning_rate = 0.008

tf.reset_default_graph()
max_step = 35000

In [4]:
# get data
dataset = np.load('dataset.npy')
labels = np.load('labels.npy')

labels.shape
dataset = dataset.T
dataset.shape

(4846, 576)

In [5]:
images_placeholder = tf.placeholder(tf.float32,shape=[3634,576])
labels_placeholder = tf.placeholder(tf.int64, shape = None)

In [6]:
#weights and biases
w = tf.get_variable('w', shape=[576,2],initializer=tf.contrib.layers.xavier_initializer(seed = 1))
b = tf.Variable(tf.zeros([2]))                

In [7]:
#function z
z = tf.matmul(images_placeholder,w) + b
#activations #1 sigmoid
z.shape


TensorShape([Dimension(3634), Dimension(2)])

In [253]:
#loss function
loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits = z,labels = labels_placeholder))

In [254]:
#training model
#train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [255]:
#prediction
# Operation comparing prediction with true label
correct_prediction = tf.equal(tf.argmax(z, 1), labels_placeholder)

# Operation calculating the accuracy of our predictions
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [256]:
#spliting the dataset into test and train sets for x and y
x_train,x_test,y_train,y_test = sk.train_test_split(dataset,labels)

x_train.shape


(3634, 576)

In [239]:
with tf.Session() as sess:
    # Initialize variables
    sess.run(tf.initialize_all_variables())
    a=[]
# Repeat max_steps times
    for i in range(max_step):
        images_batch = x_train
        labels_batch = y_train
        # Periodically print out the model's current accuracy
        if i % 100 == 0:
            train_accuracy = sess.run(accuracy, feed_dict={images_placeholder: images_batch, labels_placeholder: labels_batch})
            print('Step {:5d}: training accuracy {:g}'.format(i, train_accuracy))
            sess.run(train_step, feed_dict={images_placeholder: images_batch,labels_placeholder: labels_batch})
            a.append(train_accuracy)
    
            #print('train_step',train_step)
            # After finishing the training, evaluate on the test set
            #test_accuracy = sess.run(accuracy, feed_dict={images_placeholder: x,labels_placeholder: y})
            #print('Test accuracy {:g}'.format(test_accuracy))
        print(sess.run(w))

Step     0: training accuracy 0.516236
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.02896754 -0.08936413]
 [ 0.10410412  0.09155171]]
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.02896754 -0.08936413]
 [ 0.10410412  0.09155171]]
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.02896754 -0.08936413]
 [ 0.10410412  0.09155171]]
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.02896754 -0.08936413]
 [ 0.10410412  0.09155171]]
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.02896754 -0.08936413]
 [ 0.10410412  0.09155171]]
[[-0.04517653  0.0776651 ]
 [-0.08359239 -0.00886715]
 [ 0.07636961 -0.10449144]
 ...
 [ 0.07697655  0.08481979]
 [-0.028

[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.0919863 ]]
[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.0919863 ]]
[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.0919863 ]]
[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.0919863 ]]
[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.0919863 ]]
[[-0.04589309  0.07838167]
 [-0.08431372 -0.00814581]
 [ 0.07565312 -0.10377496]
 ...
 [ 0.07650968  0.08528665]
 [-0.029419   -0.08891266]
 [ 0.10366954  0.091

 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08566869]
 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08566869]
 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08566869]
 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08566869]
 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08566869]
 [ 0.10044014  0.09521569]]
[[-0.04936184  0.08185042]
 [-0.08778645 -0.00467308]
 [ 0.07218444 -0.10030627]
 ...
 [ 0.07325245  0.08854388]
 [-0.03266297 -0.08

[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.09983362]]
[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.09983362]]
[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.09983362]]
[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.09983362]]
[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.09983362]]
[[-0.05417456  0.08666314]
 [-0.09260238  0.00014284]
 [ 0.06737176 -0.0954936 ]
 ...
 [ 0.0686117   0.09318464]
 [-0.03729285 -0.08103881]
 [ 0.09582222  0.099

 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07915593]
 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07915593]
 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07915593]
 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07915593]
 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07915593]
 [ 0.09395321  0.10170262]]
[[-0.05627234  0.08876091]
 [-0.09470513  0.00224559]
 [ 0.06527179 -0.09339363]
 ...
 [ 0.06671494  0.09508139]
 [-0.03917573 -0.07

 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07942142]
 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07942142]
 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07942142]
 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07942142]
 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07942142]
 [ 0.09423429  0.10142155]]
[[-0.05625273  0.0887413 ]
 [-0.09469084  0.00223131]
 [ 0.06528958 -0.09341142]
 ...
 [ 0.06696543  0.0948309 ]
 [-0.03891025 -0.07

[[-0.05473042  0.087219  ]
 [-0.0931737   0.00071416]
 [ 0.06681062 -0.09493246]
 ...
 [ 0.06871996  0.09307637]
 [-0.03714097 -0.08119069]
 [ 0.09601904  0.0996368 ]]
[[-0.05473042  0.087219  ]
 [-0.0931737   0.00071416]
 [ 0.06681062 -0.09493246]
 ...
 [ 0.06871996  0.09307637]
 [-0.03714097 -0.08119069]
 [ 0.09601904  0.0996368 ]]
[[-0.05473042  0.087219  ]
 [-0.0931737   0.00071416]
 [ 0.06681062 -0.09493246]
 ...
 [ 0.06871996  0.09307637]
 [-0.03714097 -0.08119069]
 [ 0.09601904  0.0996368 ]]
[[-0.05473042  0.087219  ]
 [-0.0931737   0.00071416]
 [ 0.06681062 -0.09493246]
 ...
 [ 0.06871996  0.09307637]
 [-0.03714097 -0.08119069]
 [ 0.09601904  0.0996368 ]]
Step   700: training accuracy 0.561365
[[-0.05464806  0.08713663]
 [-0.09309491  0.00063537]
 [ 0.06689345 -0.09501529]
 ...
 [ 0.06904374  0.09275259]
 [-0.03680025 -0.08153141]
 [ 0.09637896  0.09927688]]
[[-0.05464806  0.08713663]
 [-0.09309491  0.00063537]
 [ 0.06689345 -0.09501529]
 ...
 [ 0.06904374  0.09275259]
 [-0.036

Step   800: training accuracy 0.494221
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.0378371  -0.08049456]
 [ 0.09536096  0.10029487]]
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.0378371  -0.08049456]
 [ 0.09536096  0.10029487]]
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.0378371  -0.08049456]
 [ 0.09536096  0.10029487]]
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.0378371  -0.08049456]
 [ 0.09536096  0.10029487]]
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.0378371  -0.08049456]
 [ 0.09536096  0.10029487]]
[[-0.05593718  0.08842575]
 [-0.09438781  0.00192827]
 [ 0.06560456 -0.0937264 ]
 ...
 [ 0.06799026  0.09380607]
 [-0.037

Step   900: training accuracy 0.571271
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.03972958 -0.07860208]
 [ 0.0934891   0.10216674]]
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.03972958 -0.07860208]
 [ 0.0934891   0.10216674]]
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.03972958 -0.07860208]
 [ 0.0934891   0.10216674]]
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.03972958 -0.07860208]
 [ 0.0934891   0.10216674]]
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.03972958 -0.07860208]
 [ 0.0934891   0.10216674]]
[[-0.05807943  0.090568  ]
 [-0.09653293  0.00407339]
 [ 0.06346323 -0.09158507]
 ...
 [ 0.06608067  0.09571566]
 [-0.039

[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.10264104]]
[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.10264104]]
[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.10264104]]
[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.10264104]]
[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.10264104]]
[[-0.05883105  0.09131962]
 [-0.09728786  0.00482832]
 [ 0.06271153 -0.09083337]
 ...
 [ 0.06556845  0.09622788]
 [-0.04022433 -0.07810733]
 [ 0.0930148   0.102

 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07881616]
 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07881616]
 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07881616]
 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07881616]
 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07881616]
 [ 0.0937435   0.10191234]]
[[-0.05838142  0.09086999]
 [-0.09684188  0.00438234]
 [ 0.06316046 -0.09128229]
 ...
 [ 0.06625976  0.09553657]
 [-0.0395155  -0.07

[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.10136956]]
[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.10136956]]
[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.10136956]]
[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.10136956]]
[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.10136956]]
[[-0.05813178  0.09062035]
 [-0.09659395  0.00413441]
 [ 0.0634127  -0.09153454]
 ...
 [ 0.06676056  0.09503577]
 [-0.03899471 -0.07933696]
 [ 0.09428628  0.101

[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.10177002]]
[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.10177002]]
[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.10177002]]
[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.10177002]]
[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.10177002]]
[[-0.05883066  0.09131924]
 [-0.09729404  0.0048345 ]
 [ 0.06271695 -0.09083879]
 ...
 [ 0.0663159   0.09548043]
 [-0.0394188  -0.07891286]
 [ 0.09388582  0.101

[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.10285272]]
[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.10285272]]
[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.10285272]]
[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.10285272]]
[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.10285272]]
[[-0.06021937  0.09270794]
 [-0.09868279  0.00622326]
 [ 0.06133267 -0.08945451]
 ...
 [ 0.06518729  0.09660904]
 [-0.04052677 -0.07780489]
 [ 0.09280311  0.102

[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.10321352]]
[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.10321352]]
[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.10321352]]
[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.10321352]]
[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.10321352]]
[[-0.06121631  0.09370488]
 [-0.09967986  0.00722033]
 [ 0.06034519 -0.08846703]
 ...
 [ 0.06473073  0.0970656 ]
 [-0.04093886 -0.0773928 ]
 [ 0.09244232  0.103

[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.10253848]]
[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.10253848]]
[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.10253848]]
[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.10253848]]
[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.10253848]]
[[-0.06086943  0.093358  ]
 [-0.09933294  0.00687341]
 [ 0.06069701 -0.08881886]
 ...
 [ 0.06535652  0.09643981]
 [-0.04028964 -0.07804202]
 [ 0.09311736  0.102

[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.10245011]]
[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.10245011]]
[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.10245011]]
[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.10245011]]
[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.10245011]]
[[-0.06111901  0.09360759]
 [-0.09958109  0.00712156]
 [ 0.06045477 -0.08857661]
 ...
 [ 0.06539386  0.09640247]
 [-0.04022835 -0.07810331]
 [ 0.09320573  0.102

[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.10301875]]
[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.10301875]]
[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.10301875]]
[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.10301875]]
[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.10301875]]
[[-0.06203217  0.09452075]
 [-0.1004917   0.00803217]
 [ 0.05955066 -0.0876725 ]
 ...
 [ 0.06477252  0.09702381]
 [-0.04082573 -0.07750593]
 [ 0.09263708  0.103

[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.10367998]]
[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.10367998]]
[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.10367998]]
[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.10367998]]
[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.10367998]]
[[-0.0630436   0.09553218]
 [-0.10149904  0.00903951]
 [ 0.05855134 -0.08667318]
 ...
 [ 0.06405608  0.09774026]
 [-0.04151671 -0.07681494]
 [ 0.09197585  0.103

[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.10360152]]
[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.10360152]]
[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.10360152]]
[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.10360152]]
[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.10360152]]
[[-0.06332009  0.09580867]
 [-0.1017718   0.00931227]
 [ 0.05828662 -0.08640847]
 ...
 [ 0.06407793  0.0977184 ]
 [-0.04146842 -0.07686323]
 [ 0.09205432  0.103

Step  2200: training accuracy 0.70721
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.04085538 -0.07747627]
 [ 0.09269758  0.10295826]]
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.04085538 -0.07747627]
 [ 0.09269758  0.10295826]]
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.04085538 -0.07747627]
 [ 0.09269758  0.10295826]]
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.04085538 -0.07747627]
 [ 0.09269758  0.10295826]]
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.04085538 -0.07747627]
 [ 0.09269758  0.10295826]]
[[-0.06303672  0.0955253 ]
 [-0.10148484  0.0090253 ]
 [ 0.05858143 -0.08670327]
 ...
 [ 0.06466421  0.09713212]
 [-0.0408

[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.10256113]]
[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.10256113]]
[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.10256113]]
[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.10256113]]
[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.10256113]]
[[-0.06300301  0.09549159]
 [-0.1014462   0.00898666]
 [ 0.05862943 -0.08675127]
 ...
 [ 0.06500198  0.09679435]
 [-0.04048957 -0.07784209]
 [ 0.09309471  0.102

[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.10274985]]
[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.10274985]]
[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.10274985]]
[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.10274985]]
[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.10274985]]
[[-0.0635556   0.09604418]
 [-0.10199258  0.00953305]
 [ 0.05809348 -0.08621533]
 ...
 [ 0.06475381  0.09704252]
 [-0.04071004 -0.07762162]
 [ 0.09290599  0.102

[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.10321507]]
[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.10321507]]
[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.10321507]]
[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.10321507]]
[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.10321507]]
[[-0.06438722  0.09687579]
 [-0.10281656  0.01035702]
 [ 0.05728188 -0.08540373]
 ...
 [ 0.0642264   0.09756994]
 [-0.0412082  -0.07712345]
 [ 0.09244077  0.103

[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.10322861]]
[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.10322861]]
[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.10322861]]
[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.10322861]]
[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.10322861]]
[[-0.06476989  0.09725847]
 [-0.10319146  0.01073192]
 [ 0.056919   -0.08504084]
 ...
 [ 0.0641488   0.09764753]
 [-0.04125541 -0.07707624]
 [ 0.09242723  0.103

[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.10265172]]
[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.10265172]]
[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.10265172]]
[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.10265172]]
[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.10265172]]
[[-0.06456067  0.09704924]
 [-0.10297457  0.01051504]
 [ 0.05714757 -0.08526941]
 ...
 [ 0.06466164  0.09713469]
 [-0.04071204 -0.07761961]
 [ 0.09300412  0.102

[[-0.06440564  0.09689422]
 [-0.10281072  0.01035118]
 [ 0.05732437 -0.08544622]
 ...
 [ 0.0651129   0.09668343]
 [-0.04022903 -0.07810262]
 [ 0.09352119  0.10213465]]
[[-0.06440564  0.09689422]
 [-0.10281072  0.01035118]
 [ 0.05732437 -0.08544622]
 ...
 [ 0.0651129   0.09668343]
 [-0.04022903 -0.07810262]
 [ 0.09352119  0.10213465]]
[[-0.06440564  0.09689422]
 [-0.10281072  0.01035118]
 [ 0.05732437 -0.08544622]
 ...
 [ 0.0651129   0.09668343]
 [-0.04022903 -0.07810262]
 [ 0.09352119  0.10213465]]
[[-0.06440564  0.09689422]
 [-0.10281072  0.01035118]
 [ 0.05732437 -0.08544622]
 ...
 [ 0.0651129   0.09668343]
 [-0.04022903 -0.07810262]
 [ 0.09352119  0.10213465]]
Step  2900: training accuracy 0.724546
[[-0.0647506   0.09723917]
 [-0.10314518  0.01068565]
 [ 0.05700414 -0.08512598]
 ...
 [ 0.0650587   0.09673763]
 [-0.04025124 -0.07808042]
 [ 0.09353364  0.1021222 ]]
[[-0.0647506   0.09723917]
 [-0.10314518  0.01068565]
 [ 0.05700414 -0.08512598]
 ...
 [ 0.0650587   0.09673763]
 [-0.040

[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.10241146]]
[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.10241146]]
[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.10241146]]
[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.10241146]]
[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.10241146]]
[[-0.06539115  0.09787973]
 [-0.10377371  0.01131418]
 [ 0.05639187 -0.08451372]
 ...
 [ 0.06470215  0.09709419]
 [-0.0405756  -0.07775605]
 [ 0.09324438  0.102

[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.10238836]]
[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.10238836]]
[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.10238836]]
[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.10238836]]
[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.10238836]]
[[-0.06571297  0.09820155]
 [-0.10408244  0.0116229 ]
 [ 0.05609958 -0.08422142]
 ...
 [ 0.06465698  0.09713935]
 [-0.04058809 -0.07774355]
 [ 0.09326748  0.102

[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.10182194]]
[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.10182194]]
[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.10182194]]
[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.10182194]]
[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.10182194]]
[[-0.06548499  0.09797356]
 [-0.10384075  0.01138121]
 [ 0.0563575  -0.08447935]
 ...
 [ 0.06515491  0.09664142]
 [-0.04005714 -0.0782745 ]
 [ 0.0938339   0.101

 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07874524]
 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07874524]
 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07874524]
 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07874524]
 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07874524]
 [ 0.09434056  0.10131527]]
[[-0.06530458  0.09779315]
 [-0.10364624  0.0111867 ]
 [ 0.05656916 -0.08469101]
 ...
 [ 0.06559164  0.09620469]
 [-0.0395864  -0.07

[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.10128652]]
[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.10128652]]
[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.10128652]]
[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.10128652]]
[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.10128652]]
[[-0.06559006  0.09807864]
 [-0.10391624  0.01145669]
 [ 0.0563181  -0.08443995]
 ...
 [ 0.06555022  0.09624612]
 [-0.03959415 -0.0787375 ]
 [ 0.09436932  0.101

 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07849873]
 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07849873]
 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07849873]
 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07849873]
 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07849873]
 [ 0.09416681  0.10148903]]
[[-0.06609154  0.09858012]
 [-0.10440102  0.01194148]
 [ 0.05585372 -0.08397556]
 ...
 [ 0.06527777  0.09651856]
 [-0.03983292 -0.07

 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07862948]
 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07862948]
 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07862948]
 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07862948]
 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07862948]
 [ 0.09433455  0.10132129]]
[[-0.06620944  0.09869802]
 [-0.10450189  0.01204235]
 [ 0.05577305 -0.08389489]
 ...
 [ 0.06537428  0.09642205]
 [-0.03970217 -0.07

[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.1007506 ]]
[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.1007506 ]]
[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.1007506 ]]
[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.1007506 ]]
[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.1007506 ]]
[[-0.06590958  0.09839816]
 [-0.1041848   0.01172526]
 [ 0.05611004 -0.08423188]
 ...
 [ 0.06587316  0.09592317]
 [-0.03916879 -0.07916286]
 [ 0.09490524  0.100

 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07949322]
 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07949322]
 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07949322]
 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07949322]
 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07949322]
 [ 0.09527193  0.10038391]]
[[-0.06579214  0.09828072]
 [-0.10404921  0.01158967]
 [ 0.05626695 -0.08438879]
 ...
 [ 0.06616945  0.09562688]
 [-0.03883843 -0.07

[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.10046583]]
[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.10046583]]
[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.10046583]]
[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.10046583]]
[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.10046583]]
[[-0.06610408  0.09859265]
 [-0.10434181  0.01188228]
 [ 0.05599751 -0.08411935]
 ...
 [ 0.06601744  0.09577889]
 [-0.03895668 -0.07937497]
 [ 0.09519     0.100

[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.10017739]]
[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.10017739]]
[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.10017739]]
[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.10017739]]
[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.10017739]]
[[-0.06620971  0.09869829]
 [-0.1044075   0.01194797]
 [ 0.05597841 -0.08410026]
 ...
 [ 0.06616794  0.0956284 ]
 [-0.03873948 -0.07959217]
 [ 0.09547845  0.100

[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.09974269]]
[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.09974269]]
[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.09974269]]
[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.09974269]]
[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.09974269]]
[[-0.06593576  0.09842434]
 [-0.10411296  0.01165343]
 [ 0.05629586 -0.08441771]
 ...
 [ 0.06653558  0.09526075]
 [-0.03833919 -0.07999246]
 [ 0.09591315  0.099

 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08002433]
 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08002433]
 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08002433]
 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08002433]
 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08002433]
 [ 0.09597953  0.09967631]]
[[-0.06600885  0.09849743]
 [-0.10416467  0.01170514]
 [ 0.05626887 -0.08439071]
 ...
 [ 0.06653503  0.09526131]
 [-0.03830732 -0.08

 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07985731]
 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07985731]
 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07985731]
 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07985731]
 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07985731]
 [ 0.09584629  0.09980955]]
[[-0.06625884  0.09874742]
 [-0.10439268  0.01193315]
 [ 0.05606695 -0.08418879]
 ...
 [ 0.06633653  0.0954598 ]
 [-0.03847434 -0.07

[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.09963232]]
[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.09963232]]
[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.09963232]]
[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.09963232]]
[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.09963232]]
[[-0.0661739   0.09866248]
 [-0.10428579  0.01182626]
 [ 0.05619923 -0.08432107]
 ...
 [ 0.06645063  0.0953457 ]
 [-0.03832978 -0.08000188]
 [ 0.09602351  0.099

[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.09924866]]
[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.09924866]]
[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.09924866]]
[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.09924866]]
[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.09924866]]
[[-0.06585848  0.09834706]
 [-0.10394821  0.01148867]
 [ 0.0565617  -0.08468354]
 ...
 [ 0.06677233  0.095024  ]
 [-0.03797811 -0.08035355]
 [ 0.09640718  0.099

 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08041782]
 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08041782]
 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08041782]
 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08041782]
 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08041782]
 [ 0.0965028   0.09915303]]
[[-0.06580614  0.09829471]
 [-0.10387286  0.01141332]
 [ 0.05666347 -0.0847853 ]
 ...
 [ 0.06680778  0.09498855]
 [-0.03791384 -0.08

[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.09930632]]
[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.09930632]]
[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.09930632]]
[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.09930632]]
[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.09930632]]
[[-0.06597558  0.09846416]
 [-0.10401854  0.011559  ]
 [ 0.05654545 -0.08466728]
 ...
 [ 0.06659636  0.09519997]
 [-0.03809766 -0.080234  ]
 [ 0.09634952  0.099

Step  5000: training accuracy 0.826362
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.03778052 -0.08055115]
 [ 0.09672587  0.09892996]]
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.03778052 -0.08055115]
 [ 0.09672587  0.09892996]]
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.03778052 -0.08055115]
 [ 0.09672587  0.09892996]]
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.03778052 -0.08055115]
 [ 0.09672587  0.09892996]]
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.03778052 -0.08055115]
 [ 0.09672587  0.09892996]]
[[-0.06556364  0.09805222]
 [-0.10356022  0.01110068]
 [ 0.05705562 -0.08517745]
 ...
 [ 0.06685969  0.09493664]
 [-0.037

[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.09891385]]
[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.09891385]]
[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.09891385]]
[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.09891385]]
[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.09891385]]
[[-0.06549229  0.09798086]
 [-0.10346556  0.01100602]
 [ 0.05717659 -0.08529842]
 ...
 [ 0.0668222   0.09497413]
 [-0.03779252 -0.08053915]
 [ 0.09674199  0.098

[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.09908608]]
[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.09908608]]
[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.09908608]]
[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.09908608]]
[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.09908608]]
[[-0.0655822   0.09807078]
 [-0.10353156  0.01107203]
 [ 0.05713746 -0.08525929]
 ...
 [ 0.06659947  0.09519686]
 [-0.03799157 -0.08034009]
 [ 0.09656975  0.099

[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.09901193]]
[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.09901193]]
[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.09901193]]
[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.09901193]]
[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.09901193]]
[[-0.06540629  0.09789486]
 [-0.10333276  0.01087322]
 [ 0.05736151 -0.08548334]
 ...
 [ 0.0666241   0.09517223]
 [-0.03794377 -0.0803879 ]
 [ 0.09664391  0.099

 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.0805302 ]
 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.0805302 ]
 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.0805302 ]
 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.0805302 ]
 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.0805302 ]
 [ 0.09681188  0.09884396]]
[[-0.06511389  0.09760246]
 [-0.10301784  0.0105583 ]
 [ 0.05770056 -0.08582239]
 ...
 [ 0.06674398  0.09505235]
 [-0.03780147 -0.08

[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.09893899]]
[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.09893899]]
[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.09893899]]
[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.09893899]]
[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.09893899]]
[[-0.06506398  0.09755256]
 [-0.10294586  0.01048633]
 [ 0.05779647 -0.0859183 ]
 ...
 [ 0.06660365  0.09519269]
 [-0.03792083 -0.08041085]
 [ 0.09671685  0.098

 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08022595]
 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08022595]
 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08022595]
 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08022595]
 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08022595]
 [ 0.09655476  0.09910108]]
[[-0.06506029  0.09754886]
 [-0.10291992  0.01046039]
 [ 0.05784618 -0.085968  ]
 ...
 [ 0.06639917  0.09539716]
 [-0.03810572 -0.08

[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.09901787]]
[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.09901787]]
[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.09901787]]
[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.09901787]]
[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.09901787]]
[[-0.06479562  0.0972842 ]
 [-0.10263421  0.01017468]
 [ 0.05815408 -0.08627591]
 ...
 [ 0.06644113  0.0953552 ]
 [-0.03804488 -0.0802868 ]
 [ 0.09663797  0.099

 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08029554]
 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08029554]
 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08029554]
 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08029554]
 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08029554]
 [ 0.09666765  0.09898819]]
[[-0.06456672  0.0970553 ]
 [-0.1023841   0.00992457]
 [ 0.05842611 -0.08654793]
 ...
 [ 0.0664321   0.09536424]
 [-0.03803614 -0.08

[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.09918735]]
[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.09918735]]
[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.09918735]]
[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.09918735]]
[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.09918735]]
[[-0.06455303  0.09704161]
 [-0.10235047  0.00989094]
 [ 0.05848041 -0.08660223]
 ...
 [ 0.06619691  0.09559942]
 [-0.03825497 -0.08007671]
 [ 0.09646849  0.099

[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.09929776]]
[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.09929776]]
[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.09929776]]
[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.09929776]]
[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.09929776]]
[[-0.06443708  0.09692565]
 [-0.10221573  0.0097562 ]
 [ 0.05863402 -0.08675585]
 ...
 [ 0.06605133  0.095745  ]
 [-0.03838472 -0.07994696]
 [ 0.09635808  0.099

 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07998495]
 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07998495]
 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07998495]
 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07998495]
 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07998495]
 [ 0.09641492  0.09924091]]
[[-0.06414225  0.09663083]
 [-0.10190362  0.00944409]
 [ 0.05896293 -0.08708476]
 ...
 [ 0.06607439  0.09572194]
 [-0.03834673 -0.07

[[-0.0640031   0.09649168]
 [-0.10174776  0.00928823]
 [ 0.05913471 -0.08725654]
 ...
 [ 0.06593499  0.09586134]
 [-0.03847287 -0.07985881]
 [ 0.09630641  0.09934942]]
[[-0.0640031   0.09649168]
 [-0.10174776  0.00928823]
 [ 0.05913471 -0.08725654]
 ...
 [ 0.06593499  0.09586134]
 [-0.03847287 -0.07985881]
 [ 0.09630641  0.09934942]]
[[-0.0640031   0.09649168]
 [-0.10174776  0.00928823]
 [ 0.05913471 -0.08725654]
 ...
 [ 0.06593499  0.09586134]
 [-0.03847287 -0.07985881]
 [ 0.09630641  0.09934942]]
Step  6300: training accuracy 0.843974
[[-0.06397074  0.09645932]
 [-0.10169902  0.00923949]
 [ 0.05919861 -0.08732043]
 ...
 [ 0.06568318  0.09611315]
 [-0.03871293 -0.07961874]
 [ 0.09608283  0.09957301]]
[[-0.06397074  0.09645932]
 [-0.10169902  0.00923949]
 [ 0.05919861 -0.08732043]
 ...
 [ 0.06568318  0.09611315]
 [-0.03871293 -0.07961874]
 [ 0.09608283  0.09957301]]
[[-0.06397074  0.09645932]
 [-0.10169902  0.00923949]
 [ 0.05919861 -0.08732043]
 ...
 [ 0.06568318  0.09611315]
 [-0.038

[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.09961244]]
[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.09961244]]
[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.09961244]]
[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.09961244]]
[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.09961244]]
[[-0.06374861  0.09623719]
 [-0.1014622   0.00900267]
 [ 0.05944853 -0.08757035]
 ...
 [ 0.06561655  0.09617978]
 [-0.0387685  -0.07956318]
 [ 0.09604339  0.099

[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.09964101]]
[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.09964101]]
[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.09964101]]
[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.09964101]]
[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.09964101]]
[[-0.0635155   0.09600408]
 [-0.1012156   0.00875607]
 [ 0.05970648 -0.08782831]
 ...
 [ 0.06556202  0.09623431]
 [-0.03881263 -0.07951905]
 [ 0.09601483  0.099

 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07929441]
 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07929441]
 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07929441]
 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07929441]
 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07929441]
 [ 0.09580493  0.09985091]]
[[-0.06346308  0.09595166]
 [-0.10115074  0.0086912 ]
 [ 0.05978139 -0.08790322]
 ...
 [ 0.065328    0.09646833]
 [-0.03903726 -0.07

[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.09999297]]
[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.09999297]]
[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.09999297]]
[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.09999297]]
[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.09999297]]
[[-0.06334484  0.09583341]
 [-0.10102142  0.00856188]
 [ 0.05991896 -0.08804078]
 ...
 [ 0.06516254  0.09663379]
 [-0.0391938  -0.07913787]
 [ 0.09566287  0.099

[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.10000449]]
[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.10000449]]
[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.10000449]]
[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.10000449]]
[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.10000449]]
[[-0.06309858  0.09558716]
 [-0.100766    0.00830647]
 [ 0.06018051 -0.08830234]
 ...
 [ 0.06512882  0.09666751]
 [-0.03921926 -0.07911241]
 [ 0.09565135  0.100

[[-0.06298542  0.095474  ]
 [-0.10064454  0.008185  ]
 [ 0.06030671 -0.08842854]
 ...
 [ 0.06496855  0.09682778]
 [-0.03937203 -0.07895964]
 [ 0.09551199  0.10014385]]
[[-0.06298542  0.095474  ]
 [-0.10064454  0.008185  ]
 [ 0.06030671 -0.08842854]
 ...
 [ 0.06496855  0.09682778]
 [-0.03937203 -0.07895964]
 [ 0.09551199  0.10014385]]
Step  7000: training accuracy 0.85333
[[-0.06293411  0.09542269]
 [-0.10058612  0.00812658]
 [ 0.06036833 -0.08849016]
 ...
 [ 0.06475539  0.09704094]
 [-0.03957842 -0.07875326]
 [ 0.09531832  0.10033752]]
[[-0.06293411  0.09542269]
 [-0.10058612  0.00812658]
 [ 0.06036833 -0.08849016]
 ...
 [ 0.06475539  0.09704094]
 [-0.03957842 -0.07875326]
 [ 0.09531832  0.10033752]]
[[-0.06293411  0.09542269]
 [-0.10058612  0.00812658]
 [ 0.06036833 -0.08849016]
 ...
 [ 0.06475539  0.09704094]
 [-0.03957842 -0.07875326]
 [ 0.09531832  0.10033752]]
[[-0.06293411  0.09542269]
 [-0.10058612  0.00812658]
 [ 0.06036833 -0.08849016]
 ...
 [ 0.06475539  0.09704094]
 [-0.0395

[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.10038703]]
[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.10038703]]
[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.10038703]]
[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.10038703]]
[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.10038703]]
[[-0.06274471  0.09523329]
 [-0.10039173  0.00793219]
 [ 0.06056354 -0.08868537]
 ...
 [ 0.0646873   0.09710903]
 [-0.03964033 -0.07869133]
 [ 0.09526881  0.100

[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.10045555]]
[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.10045555]]
[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.10045555]]
[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.10045555]]
[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.10045555]]
[[-0.06258342  0.09507199]
 [-0.10022663  0.0077671 ]
 [ 0.06072806 -0.08884989]
 ...
 [ 0.06460103  0.0971953 ]
 [-0.03972081 -0.07861086]
 [ 0.09520029  0.100

 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07841545]
 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07841545]
 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07841545]
 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07841545]
 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07841545]
 [ 0.09501657  0.10063927]]
[[-0.06254715  0.09503572]
 [-0.10018779  0.00772825]
 [ 0.06076456 -0.0888864 ]
 ...
 [ 0.06440032  0.09739602]
 [-0.03991622 -0.07

[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.10073832]]
[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.10073832]]
[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.10073832]]
[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.10073832]]
[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.10073832]]
[[-0.06243334  0.09492192]
 [-0.10007322  0.00761368]
 [ 0.06087483 -0.08899667]
 ...
 [ 0.06428497  0.09751137]
 [-0.04002682 -0.07830485]
 [ 0.09491751  0.100

[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.10077451]]
[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.10077451]]
[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.10077451]]
[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.10077451]]
[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.10077451]]
[[-0.06226487  0.09475345]
 [-0.09990565  0.00744612]
 [ 0.0610363  -0.08915813]
 ...
 [ 0.06423292  0.09756342]
 [-0.04007438 -0.07825729]
 [ 0.09488133  0.100

[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.10092666]]
[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.10092666]]
[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.10092666]]
[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.10092666]]
[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.10092666]]
[[-0.06222331  0.09471189]
 [-0.09986631  0.00740677]
 [ 0.06106777 -0.0891896 ]
 ...
 [ 0.06406484  0.09773149]
 [-0.0402381  -0.07809357]
 [ 0.09472918  0.100

[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.10104715]]
[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.10104715]]
[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.10104715]]
[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.10104715]]
[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.10104715]]
[[-0.06215864  0.09464723]
 [-0.09980533  0.0073458 ]
 [ 0.06111924 -0.08924107]
 ...
 [ 0.06392886  0.09786747]
 [-0.04036986 -0.07796181]
 [ 0.09460869  0.101

 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07791488]
 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07791488]
 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07791488]
 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07791488]
 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07791488]
 [ 0.09457289  0.10108294]]
[[-0.06201776  0.09450635]
 [-0.09966972  0.00721018]
 [ 0.06124379 -0.08936563]
 ...
 [ 0.06387794  0.09791839]
 [-0.04041679 -0.07

[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.10132726]]
[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.10132726]]
[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.10132726]]
[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.10132726]]
[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.10132726]]
[[-0.06193552  0.09442411]
 [-0.09960157  0.00714203]
 [ 0.06128538 -0.08940722]
 ...
 [ 0.06360328  0.09819305]
 [-0.0406841  -0.07764757]
 [ 0.09432858  0.101

[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.10137007]]
[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.10137007]]
[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.10137007]]
[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.10137007]]
[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.10137007]]
[[-0.0618259   0.09431449]
 [-0.09950069  0.00704115]
 [ 0.0613713  -0.08949314]
 ...
 [ 0.0635455   0.09825083]
 [-0.0407383  -0.07759337]
 [ 0.09428576  0.101

[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.10146465]]
[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.10146465]]
[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.10146465]]
[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.10146465]]
[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.10146465]]
[[-0.06177475  0.09426335]
 [-0.09945928  0.00699974]
 [ 0.06139654 -0.08951838]
 ...
 [ 0.06343552  0.09836081]
 [-0.04084479 -0.07748688]
 [ 0.09419119  0.101

[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.10159059]]
[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.10159059]]
[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.10159059]]
[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.10159059]]
[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.10159059]]
[[-0.06176084  0.09424943]
 [-0.09945586  0.00699633]
 [ 0.06138287 -0.08950472]
 ...
 [ 0.06329381  0.09850252]
 [-0.04098308 -0.0773486 ]
 [ 0.09406525  0.101

[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.10163998]]
[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.10163998]]
[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.10163998]]
[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.10163998]]
[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.10163998]]
[[-0.06167399  0.09416258]
 [-0.09938037  0.00692084]
 [ 0.0614406  -0.08956245]
 ...
 [ 0.06322856  0.09856777]
 [-0.04104468 -0.077287  ]
 [ 0.09401586  0.101

 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07718792]
 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07718792]
 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07718792]
 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07718792]
 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07718792]
 [ 0.09392957  0.10172627]]
[[-0.06162715  0.09411574]
 [-0.09934548  0.00688595]
 [ 0.06145702 -0.08957886]
 ...
 [ 0.06312583  0.0986705 ]
 [-0.04114376 -0.07

[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.10185052]]
[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.10185052]]
[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.10185052]]
[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.10185052]]
[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.10185052]]
[[-0.06161985  0.09410845]
 [-0.09935066  0.00689113]
 [ 0.06143273 -0.08955457]
 ...
 [ 0.06298453  0.09881181]
 [-0.04128136 -0.07705031]
 [ 0.09380532  0.101

[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.10190452]]
[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.10190452]]
[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.10190452]]
[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.10190452]]
[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.10190452]]
[[-0.06154279  0.09403139]
 [-0.09928669  0.00682716]
 [ 0.06147727 -0.08959912]
 ...
 [ 0.06291355  0.09888278]
 [-0.04134848 -0.0769832 ]
 [ 0.09375132  0.101

[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.10199983]]
[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.10199983]]
[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.10199983]]
[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.10199983]]
[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.10199983]]
[[-0.06150626  0.09399486]
 [-0.09926359  0.00680406]
 [ 0.06148048 -0.08960233]
 ...
 [ 0.06280042  0.09899591]
 [-0.04145754 -0.07687413]
 [ 0.093656    0.101

Step  9000: training accuracy 0.855806
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.04166461 -0.07666706]
 [ 0.09347728  0.10217856]]
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.04166461 -0.07666706]
 [ 0.09347728  0.10217856]]
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.04166461 -0.07666706]
 [ 0.09347728  0.10217856]]
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.04166461 -0.07666706]
 [ 0.09347728  0.10217856]]
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.04166461 -0.07666706]
 [ 0.09347728  0.10217856]]
[[-0.06141628  0.09390488]
 [-0.09920127  0.00674173]
 [ 0.0615024  -0.08962425]
 ...
 [ 0.06258436  0.09921197]
 [-0.041

[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.10229806]]
[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.10229806]]
[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.10229806]]
[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.10229806]]
[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.10229806]]
[[-0.06139665  0.09388524]
 [-0.09919579  0.00673626]
 [ 0.06148732 -0.08960916]
 ...
 [ 0.06244573  0.0993506 ]
 [-0.04179866 -0.076533  ]
 [ 0.09335778  0.102

 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07640696]
 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07640696]
 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07640696]
 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07640696]
 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07640696]
 [ 0.0932467   0.10240914]]
[[-0.06136588  0.09385448]
 [-0.09917927  0.00671973]
 [ 0.06148317 -0.08960501]
 ...
 [ 0.06231464  0.09948169]
 [-0.0419247  -0.07

 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07632582]
 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07632582]
 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07632582]
 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07632582]
 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07632582]
 [ 0.09318043  0.1024754 ]]
[[-0.06128709  0.09377568]
 [-0.09911471  0.00665517]
 [ 0.0615272  -0.08964904]
 ...
 [ 0.06222831  0.09956803]
 [-0.04200585 -0.07

[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.10262552]]
[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.10262552]]
[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.10262552]]
[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.10262552]]
[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.10262552]]
[[-0.06128718  0.09377578]
 [-0.0991291   0.00666956]
 [ 0.06149197 -0.08961381]
 ...
 [ 0.06205797  0.09973837]
 [-0.04217127 -0.0761604 ]
 [ 0.09303032  0.102

[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.10270344]]
[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.10270344]]
[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.10270344]]
[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.10270344]]
[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.10270344]]
[[-0.06121104  0.09369964]
 [-0.09906711  0.00660757]
 [ 0.06153356 -0.08965539]
 ...
 [ 0.06196011  0.09983622]
 [-0.04226422 -0.07606745]
 [ 0.09295239  0.102

[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.10295212]]
[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.10295212]]
[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.10295212]]
[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.10295212]]
[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.10295212]]
[[-0.06113859  0.09362718]
 [-0.09902271  0.00656316]
 [ 0.06153722 -0.08965905]
 ...
 [ 0.06166975  0.10012659]
 [-0.04254411 -0.07578756]
 [ 0.09270372  0.102

[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.10303985]]
[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.10303985]]
[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.10303985]]
[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.10303985]]
[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.10303985]]
[[-0.06105933  0.09354793]
 [-0.09895738  0.00649784]
 [ 0.06158235 -0.08970418]
 ...
 [ 0.06156045  0.10023589]
 [-0.04264774 -0.07568393]
 [ 0.09261598  0.103

[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.10319977]]
[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.10319977]]
[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.10319977]]
[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.10319977]]
[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.10319977]]
[[-0.06104828  0.09353688]
 [-0.09896008  0.00650053]
 [ 0.06155946 -0.08968129]
 ...
 [ 0.06137885  0.10041749]
 [-0.04282384 -0.07550783]
 [ 0.09245607  0.103

In [245]:
max(a)

0.859934

In [257]:
lr = [1,1.3,1.5,1.7,1.9,.1,.3,.5,.7,.9,.01,.03,.05,.07,0.09,.002,.004,.006,.008]
lr

[1,
 1.3,
 1.5,
 1.7,
 1.9,
 0.1,
 0.3,
 0.5,
 0.7,
 0.9,
 0.01,
 0.03,
 0.05,
 0.07,
 0.09,
 0.002,
 0.004,
 0.006,
 0.008]

In [258]:
for alpha in lr:
    a=[]
    train_step = tf.train.AdamOptimizer(learning_rate = alpha,beta1 = 0.9, beta2 = 0.99, epsilon=1e-08, use_locking=False, name='Adam').minimize(loss)
    with tf.Session() as sess:
        # Initialize variables
        sess.run(tf.initialize_all_variables())

    # Repeat max_steps times
        #loop


        
        for i in range(max_step):
            images_batch = x_train
            labels_batch = y_train
            # Periodically print out the model's current accuracy
            if i % 100 == 0:
                train_accuracy = sess.run(accuracy, feed_dict={images_placeholder: images_batch, labels_placeholder: labels_batch})
                #print('Step {:5d}: training accuracy {:g}'.format(i, train_accuracy))
                sess.run(train_step, feed_dict={images_placeholder: images_batch,labels_placeholder: labels_batch})
                a.append(train_accuracy)
        print('for alpha',alpha,'max accuracy = ',max(a))

for alpha 1 max accuracy =  0.90011007
for alpha 1.3 max accuracy =  0.898459
for alpha 1.5 max accuracy =  0.89928454
for alpha 1.7 max accuracy =  0.90011007
for alpha 1.9 max accuracy =  0.8959824
for alpha 0.1 max accuracy =  0.89900935
for alpha 0.3 max accuracy =  0.89763343
for alpha 0.5 max accuracy =  0.89543205
for alpha 0.7 max accuracy =  0.8965328
for alpha 0.9 max accuracy =  0.8965328
for alpha 0.01 max accuracy =  0.8959824
for alpha 0.03 max accuracy =  0.9050633
for alpha 0.05 max accuracy =  0.8968079
for alpha 0.07 max accuracy =  0.8998349
for alpha 0.09 max accuracy =  0.89515686
for alpha 0.002 max accuracy =  0.8717666
for alpha 0.004 max accuracy =  0.8910292
for alpha 0.006 max accuracy =  0.8979086
for alpha 0.008 max accuracy =  0.8998349
